#!/usr/bin/python
# -*- coding=utf-8 -*-

import requests
import threading
import re

url = "http://139.219.190.2:3003/park-list"
def sheetdata():
    global url
    u = url + "parks"
    header = {}
    param = {}
    param['page'] = "1" #哪一页
    param['limit'] = "3443" #每页数量
    param['park'] = "长滩基地" #哪个园区
    param['villageCommunity'] =  "长滩一社" #哪个村社
    param['productType'] =  "" #哪个产品类型
    param['breed'] = "红火树" #哪个品种
    r = requests.get(url)
    print r.content
    print r.url
    print r.headers

if __name__ == "__main__":
   sheetdata()
