#!/usr/bin/python
# -*- coding=utf-8 -*-

import requests
import threading
import re

url = "http://139.219.190.2:3003/"
def sheetdata():
    global url
    u = url + "parks"
    header = {}
    header['Cache-Control'] = "no-cache"
    param = {}
    param['page'] = "1" #哪一页
    param['limit'] = "3440" #每页数量
    param['park'] = "长滩基地" #哪个园区
    param['villageCommunity'] = "长滩一社" #哪个村社
    param['productType'] = "" #哪个产品类型
    param['breed'] = "银杏" #哪个品种
    r = requests.get(u, params=param, headers=header)
#    print r.content
    print r.url
    print r.headers
    l1 = re.compile(r'"breed":"(.*?)"')
    l2 = l1.findall(r.content)
    print l2
    print len(l2)


if __name__ == "__main__":
#   sheetdata()
    for i in range(1):
        for i in range(1):
            t = threading.Thread(target=sheetdata)
            t.start()
        t.join()
